#!/bin/bash

set -euo pipefail

bundle exec rake build:docker image=oracle:8.5
bundle exec rake build:docker image=ubuntu:20.04

bundle exec rake test image=oracle:8.5
bundle exec rake test image=ubuntu:20.04
