#!/usr/bin/env ruby
# frozen_string_literal: true

oracle = 'oracle:8.4'
ubuntu = 'ubuntu:20.04'

require 'rake/file_utils_ext'
require_relative 'lib'

include Rake::FileUtilsExt

extract_args
setup_environment

clean
buidl oracle
sh "rake test image=#{oracle}"

clean
buidl ubuntu
sh "rake test image=#{ubuntu}"
