#!/usr/bin/env ruby
# frozen_string_literal: true

oracle = 'oracle:8.5'
ubuntu = 'ubuntu:20.04'

require 'rake/file_utils_ext'
require_relative 'lib'

# rubocop:disable Style/MixinUsage
include Rake::FileUtilsExt
# rubocop:enable Style/MixinUsage

extract_args
setup_environment
clean_pkg

clean
buidl oracle
test_suite oracle

clean
buidl ubuntu
test_suite ubuntu
