#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rake/file_utils_ext'
require_relative 'lib'

include Rake::FileUtilsExt

extract_args
setup_environment

clean
buidl 'oracle:8.3'
sh 'rake test image=oracle:8.3'

clean
buidl 'ubuntu:20.04'
sh 'rake test image=ubuntu:20.04'
