#!/bin/bash

if [ -f /usr/bin/apt ]
then
  apt -y install curl apt-transport-https gnupg2
  curl 'https://keybase.io/mrstaker/pgp_keys.asc?fingerprint=8e0d38c40089f860005989acfd6652320303527f' | apt-key add -
  curl 'https://keybase.io/mrstaker/pgp_keys.asc?fingerprint=c8ff9465dc43e057f5d592eec190d4b4328516a1' | apt-key add -
  echo 'deb [arch=amd64] https://deb.staker.ltd stable main' | tee /etc/apt/sources.list.d/staker.list
  apt update

  apt install -y /build/pkg/*.deb
  exit $?
fi

if [ -f /usr/bin/dnf ]
then
  cat << 'EOF' | tee /etc/yum.repos.d/staker.repo
[staker]
name=Mr Staker rpm repository
baseurl=https://rpm.staker.ltd/$basearch/
gpgkey=https://keybase.io/mrstaker/pgp_keys.asc?fingerprint=8e0d38c40089f860005989acfd6652320303527f
       https://keybase.io/mrstaker/pgp_keys.asc?fingerprint=c8ff9465dc43e057f5d592eec190d4b4328516a1
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF

  dnf install -y /build/pkg/*.rpm
  exit $?
fi

>&2 echo 'Error: no installer available'
exit 1
