#!/bin/bash

set -euo pipefail

# build dependencies
sudo apt install curl ca-certificates build-essential git autoconf automake \
  libtool gawk alien fakeroot dkms rpm python3 python3-setuptools \
  python3-cffi python3-distlib python3-packaging linux-headers-virtual \
  libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev \
  libattr1-dev libelf-dev python3-dev libffi-dev

bundle exec rake clean
bundle exec rake build:docker image=rocky
bundle exec rake test image=rocky

bundle exec rake clean
bundle exec rake build:docker image=ubuntu
bundle exec rake test image=ubuntu
