#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(File.dirname(__FILE__), '..', 'lib')
require 'fpm'
require 'fpm/command'

# patch deb xz compression
require_relative 'patch'

exit(FPM::Command.run || 0)
