#!/bin/bash

if [ -f /usr/bin/apt ]
then
  apt -y install curl apt-transport-https gnupg2
  curl 'https://keys.openpgp.org/vks/v1/by-fingerprint/8E0D38C40089F860005989ACFD6652320303527F' | apt-key add -
  echo 'deb [arch=amd64] https://deb.staker.ltd stable main' | tee /etc/apt/sources.list.d/staker.list
  apt update

  apt install -y /build/pkg/*.deb
  exit $?
fi

if [ -f /usr/bin/dnf ]
then
  cat << 'EOF' | tee /etc/yum.repos.d/staker.repo
[staker]
name=Mr Staker rpm repository
baseurl=https://rpm.staker.ltd/$basearch/
gpgkey=https://keys.openpgp.org/vks/v1/by-fingerprint/8E0D38C40089F860005989ACFD6652320303527F
gpgcheck=1
repo_gpgcheck=1
enabled=1
EOF

  dnf install -y /build/pkg/*.rpm
  exit $?
fi

>&2 echo 'Error: no installer available'
exit 1
